>Library

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

>Load Dataset

In [2]:
heart_dataset = pd.read_csv('heart_disease.csv')

In [3]:
#For ceck (dataset)
heart_dataset.head()

age   BP  cholestrol  heart disease
0   70  130         322              1
1   67  115         564              0
2   57  124         261              1
3   64  128         263              0
4   74  120         269              0

In [4]:
#check (amount/jumlah)
heart_dataset.shape

(270, 4)

In [5]:
#pilih hasil (last pick)
heart_dataset['heart disease'].value_counts()

heart disease
0    150
1    120
Name: count, dtype: int64

In [6]:
#Memisahkan Data diaknosa dengan Label
X = heart_dataset.drop(columns='heart disease', axis=1)
Y = heart_dataset['heart disease']

In [7]:
#Test
print(X)

     age   BP  cholestrol
0     70  130         322
1     67  115         564
2     57  124         261
3     64  128         263
4     74  120         269
..   ...  ...         ...
265   52  172         199
266   44  120         263
267   56  140         294
268   57  140         192
269   67  160         286

[270 rows x 3 columns]


In [8]:
#Test Y (Variabel)
print(Y)

0      1
1      0
2      1
3      0
4      0
      ..
265    0
266    0
267    0
268    0
269    1
Name: heart disease, Length: 270, dtype: int64


>Standarisasi Data

In [9]:
scaler = StandardScaler()

In [10]:
#Scale Variabel (X)
scaler.fit(X)

StandardScaler()

In [11]:
#standar data
standarized_data = scaler.transform(X)

In [12]:
#check variabel
print(standarized_data)

[[ 1.71209356 -0.07540984  1.40221232]
 [ 1.38213977 -0.91675934  6.0930045 ]
 [ 0.2822938  -0.41194964  0.21982255]
 [ 1.05218598 -0.18758978  0.25858943]
 [ 2.15203195 -0.63630951  0.37489006]
 [ 1.16217058 -0.63630951 -1.4083863 ]
 [ 0.1723092  -0.07540984  0.12290536]
 [ 0.50226299 -1.19720918 -0.2066131 ]
 [ 0.61224759  0.48548982  0.84009259]
 [ 0.94220138  1.04638949  3.04980461]
 [ 0.50226299  0.20503999 -0.30353029]
 [-0.15764459  0.59766975 -0.4585978 ]
 [-1.14750596  0.48548982 -0.28414685]
 [ 0.72223219  0.14895002 -0.30353029]
 [ 0.2822938  -0.18758978  1.03392698]
 [ 1.82207816 -1.08502924 -1.95112259]
 [-0.92753677  0.48548982  1.18899449]
 [-0.15764459  0.48548982 -0.90441689]
 [ 1.05218598 -1.19720918 -0.74934938]
 [-1.58744435  0.48548982 -0.98195065]
 [ 1.38213977 -0.63630951 -0.40044749]
 [-0.70756757 -0.07540984 -0.09031247]
 [-1.25749056 -0.91675934  1.03392698]
 [-0.81755217 -1.08502924 -0.88503346]
 [-0.04765999  0.03677009  0.7431754 ]
 [-0.70756757 -0.07540984

In [13]:
#Definisikan
X = standarized_data
Y = heart_dataset['heart disease']

In [14]:
#checkking
print(X)
print(Y)

[[ 1.71209356 -0.07540984  1.40221232]
 [ 1.38213977 -0.91675934  6.0930045 ]
 [ 0.2822938  -0.41194964  0.21982255]
 [ 1.05218598 -0.18758978  0.25858943]
 [ 2.15203195 -0.63630951  0.37489006]
 [ 1.16217058 -0.63630951 -1.4083863 ]
 [ 0.1723092  -0.07540984  0.12290536]
 [ 0.50226299 -1.19720918 -0.2066131 ]
 [ 0.61224759  0.48548982  0.84009259]
 [ 0.94220138  1.04638949  3.04980461]
 [ 0.50226299  0.20503999 -0.30353029]
 [-0.15764459  0.59766975 -0.4585978 ]
 [-1.14750596  0.48548982 -0.28414685]
 [ 0.72223219  0.14895002 -0.30353029]
 [ 0.2822938  -0.18758978  1.03392698]
 [ 1.82207816 -1.08502924 -1.95112259]
 [-0.92753677  0.48548982  1.18899449]
 [-0.15764459  0.48548982 -0.90441689]
 [ 1.05218598 -1.19720918 -0.74934938]
 [-1.58744435  0.48548982 -0.98195065]
 [ 1.38213977 -0.63630951 -0.40044749]
 [-0.70756757 -0.07540984 -0.09031247]
 [-1.25749056 -0.91675934  1.03392698]
 [-0.81755217 -1.08502924 -0.88503346]
 [-0.04765999  0.03677009  0.7431754 ]
 [-0.70756757 -0.07540984

>Data Training and Testing

In [15]:
#Identifikasi
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [16]:
#checking
print(X.shape, X_train.shape, X_test.shape)

(270, 3) (216, 3) (54, 3)


>Creat Data, use Algo SVM

In [17]:
classifier = svm.SVC(kernel='linear')

In [18]:
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

>Creat Evaluation for (measure the degree of accuracy)

In [19]:
#Untuk perintah deteksi
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [20]:
#View
print('Akurasi data Training = ', training_data_accuracy)

Akurasi data Training =  0.6157407407407407


In [21]:
#Data testing check
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [22]:
#View check
print('Akurasi data Testing = ', test_data_accuracy)

Akurasi data Testing =  0.6111111111111112


>Creat Prediction Models

In [23]:
#Array
#Data awal in dataset
input_data = (63, 150, 407)

input_data_as_numpy_array = np.array(input_data)

input_data_reshape = input_data_as_numpy_array.reshape(1,-1)

std_data = scaler.transform(input_data_reshape)
print(std_data)

#Hasil prediction
prediction = classifier.predict(std_data)
print(prediction)

#Kondisi
if (prediction[0] == 1):
  print('Pasien terkena penyakit Jantung')
else :
  print('Pasien tidak mempunyai penyakit Jantung')

[[0.94220138 1.04638949 3.04980461]]
[1]
Pasien terkena penyakit Jantung


c:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


>Save Models

In [24]:
#Library
import pickle

In [25]:
#Save name
filename = 'heart_disease3_model.sav'
pickle.dump(classifier, open(filename, 'wb'))

# Misalkan model Anda disimpan dalam variabel 'model'
#pickle.dump(classifier, 'Heart.sav')